version: 0.0

os: linux

files:
  - source: files/index.html
    destination: /var/www/html


permission:
  - object: /var/www/html
    pattern: index.html
    owner: apache
    group: apache
    mode: 644
    type:
      - file

hooks:
  BeforeInstall:
  - location: scripts/deregister_from_elb.sh
  - location: scripts/webserver-stop.sh
  - location: scripts/delete-old-index.sh
  AfterInstall:
  - location: scripts/sleep.sh
  - location: scripts/webserver-start.sh
  - location: scripts/register_with_elb.sh

